### ISSUE TITLE
"this" Keyword

### ISSUE THREAD

**Issue by dennisdoomen** [dennisdoomen/CSharpGuidelines#2]
_Reported by [@ggondim](https://www.codeplex.com/site/users/view/ggondim) via [CodePlex](https://csharpguidelines.codeplex.com/workitem/11345):_

In most project cases, the use of "this" keyword inside a class is unregulated and some developers use it in a way an some others use in another way. 

It is really important to regulate the use of the keyword. It is useful in some cases to identify a class member inside a method with many variables, but it is also useless inside a constructor, factory method or even a overloaded method. 

I particullary think the use of "this" keyword is only needed on constructor calling and indexable class properties, like below:

```
public class MyClass
{
    public MyClass() : this(false)
    { }

    public MyClass(bool enableConfiguration)
    {
    }
}
```

and:

```
public MyClass
{
    this[int index]
    {
        get { return list.ElementAt(index); }
    }
}  
```

It is also a "standard" proposed in IDesign C# Coding Standard.

**Comment by dg9ngf** [comment]
I'd vote for not using `this.` and `base.` prefixes unless it's required. In a class hierarchy, it's not necessary to know on which level something is to use it. Refactoring derived classes is harder if that level is fixed in the code. (Interesting read: http://blog.codinghorror.com/the-best-code-is-no-code-at-all/)

Where these keywords are not used as prefix (i. e. `this` alone as a reference or both when calling another or a base constructor), it should be clear that it's not an option to leave them out.

**Comment by dennisdoomen** [comment]
:+1:

**Comment by Shane88** [comment]
I vote for not using `this.` as well. The common case I see it used is in constructors, such as.

```cs
public class MyClass
{
    private IDependency dependency;

    public MyClass(IDependency dependency)
    {
        // this. prefix is required because the parameter shadows the field.
        this.dependency = dependency;
    }
}
```

Something I feel is related is I have adopted the style of prefixing private members with an underscore, which means the assignment no longer needs the `this.` prefix. You will see that the CoreFX repo adheres to this style as well https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md see style number 3, copied here for convenience:

> We use _camelCase for internal and private fields and use readonly where possible. Prefix instance
fields with _, static fields with s_ and thread static fields with t_. When used on static fields, readonly  should come after static (i.e. static readonly not readonly static). 

This currently conflicts with the recommendation in this set of guidelines https://github.com/dennisdoomen/CSharpGuidelines/blob/master/Src/Guidelines/1700_NamingGuidelines.md#-dont-prefix-fields--av1705- copied here for convenience:

> Don't prefix fields (AV1705) 
> 
> For example, don't use g_ or s_ to distinguish static from non-static fields. A method in which it is difficult to distinguish local variables from member fields is generally too big. Examples of incorrect identifier names are: _currentUser, mUserName, m_loginTime.

**Comment by cocowalla** [comment]
@Shane88 `this` seems to be very much a matter of personal preference, almost as bad as tabs vs spaces :)

> Something I feel is related is I have adopted the style of prefixing private members with an underscore, which means the assignment no longer needs the this. prefix.

Personally, it feels wrong to invent your own prefix scheme (e.g. `_`) when C# has a built-in keyword for exactly this case - `this`.

**Comment by SaroTasciyan** [comment]
For me, I don't prefer using any kind of _prefix_ since I find it less readable. I also agree with @cocowalla and [Eric Lippert](http://stackoverflow.com/questions/8006494/c-sharp-net-instance-variable-naming-convention/8015280#8015280) that it isn't necessary.

I'd rather use `this` only when it is required. And having my private fields named without a prefix using `this` keyword becomes required.
