### ISSUE TITLE
Should AV1540 really exist?

### ISSUE THREAD

**Issue by SamirHafez** [dennisdoomen/CSharpGuidelines#23]
> Be reluctant with multiple return statements (AV1540) 

> One entry, one exit is a sound principle and keeps control flow readable. However, if the method is very small and complies with guideline AV1500 then multiple return statements may actually improve readability over some central boolean flag that is updated at various points.

I think having multiple return statements actually improve code readability (independently of method size) when we use [guard statements](http://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).

These guard statements are essential for preventing something like the [Arrow Anti-Pattern](http://c2.com/cgi/wiki?ArrowAntiPattern).

Thoughts?

**Comment by dennisdoomen** [comment]
I'm in doubt as well. But the reason why I kept it in it, because a lot of people end up ignoring [AV1500](https://github.com/dennisdoomen/csharpguidelines/blob/master/Guidelines/1500_MaintainabilityGuidelines.md#methods-should-not-exceed-7-statements-av1500-) and write long methods. Having multiple return statements in long methods is going to make it pretty difficult to read.
